extends Node

var user_data


const leader_stat_color = {
	"Dominance" : Color.ORANGE,
	"Power" : Color.RED,
	"Agility" : Color.WHITE,
	"Fear" : Color.DEEP_PINK,
	"Vigilance" : Color.SPRING_GREEN,
	"Pride" : Color.YELLOW,
	"Intellect" : Color.CYAN
}

var card_database = {
	"lad_test": {
		"name" : "_test",
		"title" : "memaybeo",
		"left" : 0,
		"right" : 0,
		"middle" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : -1},
		"effect_bottom" : {"side" : "m" , "stat" : -1},
		"ability" : "Cocaidai",
		"type" : "Lad",
		"region" : "Aouni"
	},
	"leader_test": {
		"name" : "_thu",
		"title" : "The leader test",
		"left" : "Dominance",
		"right" : "Agility",
		"middle" : "Vigilance",
		"ability" : "test leader ability",
		"type" : "Leader",
		"region" : "Aouni"
	},
	"lad_reinalia_amelia": {
		"name" : "Amelia",
		"title" : "The loyal",
		"left" : 2,
		"middle" : 1,
		"right" : 2,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "On play: Move another ally Lad",
		"type" : "Lad",
		"region" : "Reinalia"
	},
	"lad_tikkers_arthur": {
		"name" : "Arthur",
		"title" : "The brave",
		"left" : 3,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "m" , "stat" : 2},
		"effect_right" : {"side" : "m" , "stat" : 2},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Tikkers"
	},
	"lad_aouni_baelin": {
		"name" : "Baelin",
		"title" : "The bara",
		"left" : 1,
		"middle" : 3,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 2},
		"effect_bottom" : {"side" : "m" , "stat" : 2},
		"ability" : "",
		"type" : "Lad",
		"region" : "Aouni"
	},
	"lad_wildcardz_dangor": {
		"name" : "Dangor",
		"title" : "The gengar",
		"left" : 2,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When my stat values gets increased: Increase it by twice the amount",
		"type" : "Lad",
		"region" : "Wildcardz"
	},
	"lad_thyena_diego": {
		"name" : "Diego",
		"title" : "The dangerous",
		"left" : 2,
		"middle" : 2,
		"right" : 2,
		"effect_left" : {"side" : "r" , "stat" : -1},
		"effect_right" : {"side" : "r" , "stat" : -1},
		"effect_top" : {"side" : "r" , "stat" : -1},
		"effect_bottom" : {"side" : "r" , "stat" : -1},
		"ability" : "I only affect ally Lads stats",
		"type" : "Lad",
		"region" : "Thyena"
	},
	"lad_wildcardz_drifter": {
		"name" : "Drifter",
		"title" : "The drifter",
		"left" : 0,
		"middle" : 0,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "On play: Our leader gains +1 stat point of choice for every 2 cards in our draw pile",
		"type" : "Lad",
		"region" : "Wildcardz"
	},
	"lad_wildcardz_ellie": {
		"name" : "Ellie",
		"title" : "The kind",
		"left" : 1,
		"middle" : 1,
		"right" : 3,
		"effect_left" : {"side" : "l" , "stat" : 2},
		"effect_right" : {"side" : "l" , "stat" : 2},
		"effect_top" : {"side" : "l" , "stat" : 2},
		"effect_bottom" : {"side" : "l" , "stat" : 2},
		"ability" : "",
		"type" : "Lad",
		"region" : "Wildcardz"
	},
	"lad_mysticle_ghost": {
		"name" : "Ghost",
		"title" : "The order's order",
		"left" : 2,
		"middle" : 2,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "Lads in front of me cannot have their stats changed",
		"type" : "Lad",
		"region" : "Mysticle"
	},
	"lad_reinalia_gorloch": {
		"name" : "Gorloch",
		"title" : "The eater of the worlds",
		"left" : 1,
		"middle" : 3,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 1},
		"ability" : "When I get moved: Move all adjacent Lads with me in the same position. The place I move must have enough room for me and my Lads to occupy",
		"type" : "Lad",
		"region" : "Reinalia"
	},
	"lad_kahn_gorlon": {
		"name" : "Gorlon",
		"title" : "The large",
		"left" : 0,
		"middle" : 5,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "I cannot be moved or swapped",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_kahn_hoang_xiang": {
		"name" : "Hoang Xiang",
		"title" : "The entitled",
		"left" : 2,
		"middle" : 2,
		"right" : 2,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "My stats values cannot be changed",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_kahn_hsu_tao": {
		"name" : "Hsu Tao",
		"title" : "The red right hand",
		"left" : 2,
		"middle" : 0,
		"right" : 3,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When I get swapped while in play: Choose another enemy Lad to get swapped instead",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_tikkers_james": {
		"name" : "James",
		"title" : "The lovable douchebag",
		"left" : 1,
		"middle" : 3,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 2},
		"effect_right" : {"side" : "r" , "stat" : 2},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Tikkers"
	},
	"lad_thyena_kiel": {
		"name" : "Kiel",
		"title" : "Thyena",
		"left" : 3,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "r" , "stat" : 2},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Thyena"
	},
	"lad_wildcardz_knightmare": {
		"name" : "Knightmare",
		"title" : "The late",
		"left" : 0,
		"middle" : 0,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "On play: Our leader gains +1 stat point to the total stat value for every card in our discard pile",
		"type" : "Lad",
		"region" : "Wildcardz"
	},
	"lad_wildcardz_krauss": {
		"name" : "Krauss",
		"title" : "The killer",
		"left" : 2,
		"middle" : 1,
		"right" : 2,
		"effect_left" : {"side" : "r" , "stat" : 1},
		"effect_right" : {"side" : "r" , "stat" : 1},
		"effect_top" : {"side" : "r" , "stat" : 1},
		"effect_bottom" : {"side" : "r" , "stat" : 1},
		"ability" : "I get +1 [img]res://game-components/card/bar_icon/l.png[/img], [img]res://game-components/card/bar_icon/m.png[/img] for every adjacent Lad",
		"type" : "Lad",
		"region" : "Wildcardz"
	},
	"lad_reinalia": {
		"name" : "Leena",
		"title" : "The victorian secret",
		"left" : 0,
		"middle" : 5,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : -2},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Reinalia"
	},
	"lad_mysticle_lynx": {
		"name" : "Lynx",
		"title" : "Mysticle",
		"left" : 4,
		"middle" : 0,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "On play/When I get swapped from hand to play: Swap me with an enemy Lad",
		"type" : "Lad",
		"region" : "Mysticle"
	},
	"lad_aouni_madame_bo": {
		"name" : "Madame Bo",
		"title" : "The lady",
		"left" : 0,
		"middle" : 0,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "On play: Swap me with an ally Lad in our discard pile",
		"type" : "Lad",
		"region" : "Aouni"
	},
	"lad_thyena_marco": {
		"name" : "Marco",
		"title" : "The timid tomboy",
		"left" : 3,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 2},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Thyena"
	},
	"lad_thyena_mariannah": {
		"name" : "Mariannah",
		"title" : "The little",
		"left" : 1,
		"middle" : 1,
		"right" : 3,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When my stats gets increased: the Lad that increased my stats also has their stats increased by the same amount",
		"type" : "Lad",
		"region" : "Thyena"
	},
	"lad_thyena_miguel": {
		"name" : "Miguel",
		"title" : "The marvelous",
		"left" : 3,
		"middle" : 3,
		"right" : 3,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "I get -1 [img]res://game-components/card/bar_icon/l.png[/img], [img]res://game-components/card/bar_icon/m.png[/img], [img]res://game-components/card/bar_icon/r.png[/img] for every adjacent Lad",
		"type" : "Lad",
		"region" : "Thyena"
	},
	"lad_reinalia_millie": {
		"name" : "Millie",
		"title" : "THe guardian",
		"left" : 5,
		"middle" : 0,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "m" , "stat" : -2},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Reinalia"
	},
	"lad_tikkers_nathan": {
		"name" : "Nathan",
		"title" : "The indifferent",
		"left" : 0,
		"middle" : 0,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "My [img]res://game-components/card/bar_icon/l.png[/img], [img]res://game-components/card/bar_icon/m.png[/img], [img]res://game-components/card/bar_icon/r.png[/img] are the same as the base [img]res://game-components/card/bar_icon/l.png[/img], [img]res://game-components/card/bar_icon/m.png[/img], [img]res://game-components/card/bar_icon/r.png[/img] from the Lad on my right",
		"type" : "Lad",
		"region" : "Tikkers"
	},
	"lad_mysticle_polo": {
		"name" : "Polo",
		"title" : "The joke",
		"left" : 1,
		"middle" : 1,
		"right" : 3,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "Lads behind me cannot be moved or swapped",
		"type" : "Lad",
		"region" : "Mysticle"
	},
	"lad_kahn_quan_tran": {
		"name" : "Quan Tran",
		"title" : "The misguided",
		"left" : 1,
		"middle" : 2,
		"right" : 2,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "My stats value cannot be decreased",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_kahn_raven": {
		"name" : "Raven",
		"title" : "The relentless",
		"left" : 0,
		"middle" : 3,
		"right" : 2,
		"effect_left" : {"side" : "l" , "stat" : -2},
		"effect_right" : {"side" : "l" , "stat" : -2},
		"effect_top" : {"side" : "l" , "stat" : -2},
		"effect_bottom" : {"side" : "l" , "stat" : -2},
		"ability" : "",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_kahn_saigon": {
		"name" : "Saigon",
		"title" : "The savage",
		"left" : 2,
		"middle" : 3,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "On play: Move an adjacent Lad to another adjacent position",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_aouni_sealyn": {
		"name" : "Sealyn",
		"title" : "The shaolin appprentice",
		"left" : 0,
		"middle" : 8,
		"right" : 0,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "Only my [img]res://game-components/card/bar_icon/m.png[/img]'s value may be changed",
		"type" : "Lad",
		"region" : "Aouni"
	},
	"lad_aouni_seymour": {
		"name" : "Seymour",
		"title" : "The master",
		"left" : 1,
		"middle" : 2,
		"right" : 2,
		"effect_left" : {"side" : "m" , "stat" : 2},
		"effect_right" : {"side" : "m" , "stat" : 2},
		"effect_top" : {"side" : "m" , "stat" : 2},
		"effect_bottom" : {"side" : "m" , "stat" : 2},
		"ability" : "",
		"type" : "Lad",
		"region" : "Aouni"
	},
	"lad_mysticle_shin": {
		"name" : "Shin",
		"title" : "The weakest one",
		"left" : 1,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When I get swapped or moved: Our leader gains +1 stat point of choice",
		"type" : "Lad",
		"region" : "Mysticle"
	},
	"lad_mysticle_song": {
		"name" : "Song",
		"title" : "The mistres of the night",
		"left" : 1,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When an Lad gets swapped or moved: Our leader gains +1 stat point of choice",
		"type" : "Lad",
		"region" : "Mysticle"
	},
	"lad_reinalia_tanaya": {
		"name" : "Tanaya",
		"title" : "The advisor",
		"left" : 1,
		"middle" : 2,
		"right" : 2,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When I get moved: Swap me with another ally Lad instead",
		"type" : "Lad",
		"region" : "Reinalia"
	},
	"lad_tikkers_thomas": {
		"name" : "Thomas",
		"title" : "The tank",
		"left" : 1,
		"middle" : 1,
		"right" : 3,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "r" , "stat" : 2},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "",
		"type" : "Lad",
		"region" : "Tikkers"
	},
	"lad_tikkers_tyler": {
		"name" : "Tyler",
		"title" : "The edgy",
		"left" : 4,
		"middle" : 4,
		"right" : 4,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When my stat values gets decreased: Decrease it by twice the amount",
		"type" : "Lad",
		"region" : "Tikkers"
	},
	"lad_kahn_xu_fuang": {
		"name" : "Xu Fuang",
		"title" : "The warrior",
		"left" : 1,
		"middle" : 3,
		"right" : 1,
		"effect_left" : {"side" : "m" , "stat" : 2},
		"effect_right" : {"side" : "m" , "stat" : 2},
		"effect_top" : {"side" : "r" , "stat" : -2},
		"effect_bottom" : {"side" : "r" , "stat" : -2},
		"ability" : "",
		"type" : "Lad",
		"region" : "Kahn"
	},
	"lad_aouni_yuniko": {
		"name" : "Yuniko",
		"title" : "The princess",
		"left" : 1,
		"middle" : 1,
		"right" : 1,
		"effect_left" : {"side" : "l" , "stat" : 0},
		"effect_right" : {"side" : "r" , "stat" : 0},
		"effect_top" : {"side" : "m" , "stat" : 0},
		"effect_bottom" : {"side" : "m" , "stat" : 0},
		"ability" : "When an ally Lad enters play: Our Leader gains +1 stat point of choice",
		"type" : "Lad",
		"region" : "Aouni"
	},
	"leader_thyena_citrious": {
		"name" : "Citrious",
		"title" : "The call of nature",
		"left" : "Pride",
		"middle" : "Vigilance",
		"right" : "Power",
		"ability" : "When ally Lads stats gets increased: Decrease it instead \nWhen ally Lads stats gets decreased: Increase it instead",
		"type" : "Leader",
		"region" : "Thyena"
	},
	"leader_tikkers_strong_john": {
		"name" : "Strong John",
		"title" : "The royal",
		"left" : "Power",
		"middle" : "Pride",
		"right" : "Intellect",
		"ability" : "Start the game with +5 [img]res://game-components/card/bar_icon/l.png[/img], [img]res://game-components/card/bar_icon/m.png[/img], [img]res://game-components/card/bar_icon/r.png[/img]",
		"type" : "Leader",
		"region" : "Tikkers"
	},
	"leader_aouni_leviathan": {
		"name" : "Leviathan",
		"title" : "The world's serpent",
		"left" : "Intellect",
		"middle" : "Dominance",
		"right" : "Fear",
		"ability" : "End of Game: Win the game if we have highest total amount of points",
		"type" : "Leader",
		"region" : "Aouni"
	},
	"leader_mysticle_lotus": {
		"name" : "Lotus",
		"title" : "The ghost",
		"left" : "Fear",
		"middle" : "Agility",
		"right" : "Vigilance",
		"ability" : "Once per Turn: Swap an ally Lad in play with a Lad in hand",
		"type" : "Leader",
		"region" : "Mysticle"
	},
	"leader_wildcardz_major_dmora": {
		"name" : "Major Dmora",
		"title" : "The champion",
		"left" : "Vigilance",
		"middle" : "Intellect",
		"right" : "Agility",
		"ability" : "Once per Game: Pick a card from our discard pile and put it in play",
		"type" : "Leader",
		"region" : "Wildcardz"
	},
	"leader_kahn_shaojinko": {
		"name" : "Shaojinko",
		"title" : "The general",
		"left" : "Dominance",
		"middle" : "Power",
		"right" : "Pride",
		"ability" : "Start of Game",
		"type" : "Leader",
		"region" : "Kahn"
	},
	"leader_reinalia_sindella": {
		"name" : "Sindella",
		"title" : "The envious",
		"left" : "Agility",
		"middle" : "Fear",
		"right" : "Dominance",
		"ability" : "Once per Turn: Move another ally Lad in play",
		"type" : "Leader",
		"region" : "Reinalia"
	},
}
